In [23]:
import pandas as pd
from Bio import SeqIO
import numpy as np

In [29]:
upar = pd.read_csv('data/SD1_Dataset_and_information.csv')
upar

,identifier,group,membran_prediction,taxon_of_interest,family,genus,species,taxon_id,db,uniprot_id,...,refseq_id,gi_number,in_tree,seq_start,full_seq,mature_seq,pdb_id,LDDT,TM_score,RMSD
0,None|Xetr_1|Xenopus_tropicalis,frog Ly6,Membrane,Anura,Pipidae,Xenopus,Xenopus tropicalis,8364,NaN,NaN,...,NaN,NaN,yes,MAA,MAALYISLLLAALCIGTAVPLRCYTCTGATNANCLTQTDCGSTNTS...,LRCYTCTGATNANCLTQTDCGSTNTSCATVVGSVLGQPIIIKSCTL...,NaN,NaN,NaN,NaN
1,None|Xetr_2|Xenopus_tropicalis,frog Ly6,Secreted,Anura,Pipidae,Xenopus,Xenopus tropicalis,8364,NaN,NaN,...,NaN,NaN,yes,MQC,MQCYMCLGATSNANCLTPTTCRSYDAYCQTVSSASITKYCAPSCTP...,MQCYMCLGATSNANCLTPTTCRSYDAYCQTVSSASITKYCAPSCTP...,NaN,NaN,NaN,NaN
2,None|Xetr_3|Xenopus_tropicalis,frog Ly6,Membrane,Anura,Pipidae,Xenopus,Xenopus tropicalis,8364,NaN,NaN,...,NaN,NaN,yes,NaN,NaN,LKCYTCTSAPTNAECLTLTTCRSYDAYCETVVRSSSIARASGTISC...,NaN,NaN,NaN,NaN
3,None|Xetr_5|Xenopus_tropicalis,frog Ly6,Membrane,Anura,Pipidae,Xenopus,Xenopus tropicalis,8364,NaN,NaN,...,NaN,NaN,yes,MAD,MADLRVVLVLTALCIGTAVSLTCYTCSGQSTNTNCMTATNCTASQT...,LTCYTCSGQSTNTNCMTATNCTASQTYCKTSVIAGGIGSLSAATIT...,NaN,NaN,NaN,NaN
4,None|Xetr_6|Xenopus_tropicalis,frog Ly6,Membrane,Anura,Pipidae,Xenopus,Xenopus tropicalis,8364,NaN,NaN,...,NaN,NaN,yes,MSP,MSPYRYKGEYKGELGELGTHSTATPSLTMAALYGSLLLAALCIGTA...,LKCYTCTGESSNANCLNQTNCSDIDTSCQTFVASISLFGVSAKSIT...,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1422,None|B.multicinctus_HiC_scaffold7_G00800.t1|Bu...,Ly6 other,Membrane,Elapidae,Elapidae,Bungarus,Bungarus multicinctus,8616,NaN,NaN,...,NaN,NaN,no,MPA,MPAGMKAPLAILLAACLCVDGVFSLVCWSCENVESNWGCWRTQICP...,LVCWSCENVESNWGCWRTQICPDGFNYCATTYTGAGIGEYSAQSIS...,NaN,NaN,NaN,NaN
1423,None|B.multicinctus_HiC_scaffold7_G00801.t1|Bu...,Ly6 other,Membrane,Elapidae,Elapidae,Bungarus,Bungarus multicinctus,8616,NaN,NaN,...,NaN,NaN,no,MLS,MLSDAGAAAASSSSSGPFSRHRPLTMKPLFAALLAGLLCMQTAMSS...,SLICISCDKVDHNSKCYDLKVCDEDNDRYCYTKYFGTGSGENHKEM...,NaN,NaN,NaN,NaN
1424,None|denovo_2_scaffold7|Bungarus_multicinctus,Plesiotypic,Secreted,Elapidae,Elapidae,Bungarus,Bungarus multicinctus,8616,NaN,NaN,...,NaN,NaN,no,MKT,MKTLLLILVVVTLVCPDLAHTLICHSCTGALCPGHEQCPDGQKLCY...,LICHSCTGALCPGHEQCPDGQKLCYGKWNKTDVFIIRGCAATCPTE...,NaN,NaN,NaN,NaN
1425,None|ScVE01q_1072_HRSCAF_1231_-_32|Naja_naja,Short-chain,Secreted,Elapidae,Elapidae,Naja,Naja naja,35670,NaN,NaN,...,NaN,NaN,no,MKT,MKTLLLTLVVVTIVCLDLGYTLKCHNTQLPLIYKTCPEGKNLCFKM...,LKCHNTQLPLIYKTCPEGKNLCFKMTLKRFPLKFPVKRGCAATCPK...,NaN,NaN,NaN,NaN
1426,None|ScVE01q_1072_HRSCAF_1231_-_33|Naja_naja,Short-chain,Secreted,Elapidae,Elapidae,Naja,Naja naja,35670,NaN,NaN,...,NaN,NaN,no,MKT,MKTLLLTLVVVTIVCLDLGSTLKCNKLIPLAYKTCPAGKNLCYKMY...,LKCNKLIPLAYKTCPAGKNLCYKMYMVGCIDVCPKNSLLVKYVCCN...,NaN,NaN,NaN,NaN

In [30]:
upar["Fragment"] = upar["full_seq"].apply(lambda x: "full_seq (SP)" if pd.notna(x) else "mature_seq (NO_SP)")
upar

,identifier,group,membran_prediction,taxon_of_interest,family,genus,species,taxon_id,db,uniprot_id,...,gi_number,in_tree,seq_start,full_seq,mature_seq,pdb_id,LDDT,TM_score,RMSD,Fragment
0,None|Xetr_1|Xenopus_tropicalis,frog Ly6,Membrane,Anura,Pipidae,Xenopus,Xenopus tropicalis,8364,NaN,NaN,...,NaN,yes,MAA,MAALYISLLLAALCIGTAVPLRCYTCTGATNANCLTQTDCGSTNTS...,LRCYTCTGATNANCLTQTDCGSTNTSCATVVGSVLGQPIIIKSCTL...,NaN,NaN,NaN,NaN,full_seq (SP)
1,None|Xetr_2|Xenopus_tropicalis,frog Ly6,Secreted,Anura,Pipidae,Xenopus,Xenopus tropicalis,8364,NaN,NaN,...,NaN,yes,MQC,MQCYMCLGATSNANCLTPTTCRSYDAYCQTVSSASITKYCAPSCTP...,MQCYMCLGATSNANCLTPTTCRSYDAYCQTVSSASITKYCAPSCTP...,NaN,NaN,NaN,NaN,full_seq (SP)
2,None|Xetr_3|Xenopus_tropicalis,frog Ly6,Membrane,Anura,Pipidae,Xenopus,Xenopus tropicalis,8364,NaN,NaN,...,NaN,yes,NaN,NaN,LKCYTCTSAPTNAECLTLTTCRSYDAYCETVVRSSSIARASGTISC...,NaN,NaN,NaN,NaN,mature_seq (NO_SP)
3,None|Xetr_5|Xenopus_tropicalis,frog Ly6,Membrane,Anura,Pipidae,Xenopus,Xenopus tropicalis,8364,NaN,NaN,...,NaN,yes,MAD,MADLRVVLVLTALCIGTAVSLTCYTCSGQSTNTNCMTATNCTASQT...,LTCYTCSGQSTNTNCMTATNCTASQTYCKTSVIAGGIGSLSAATIT...,NaN,NaN,NaN,NaN,full_seq (SP)
4,None|Xetr_6|Xenopus_tropicalis,frog Ly6,Membrane,Anura,Pipidae,Xenopus,Xenopus tropicalis,8364,NaN,NaN,...,NaN,yes,MSP,MSPYRYKGEYKGELGELGTHSTATPSLTMAALYGSLLLAALCIGTA...,LKCYTCTGESSNANCLNQTNCSDIDTSCQTFVASISLFGVSAKSIT...,NaN,NaN,NaN,NaN,full_seq (SP)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1422,None|B.multicinctus_HiC_scaffold7_G00800.t1|Bu...,Ly6 other,Membrane,Elapidae,Elapidae,Bungarus,Bungarus multicinctus,8616,NaN,NaN,...,NaN,no,MPA,MPAGMKAPLAILLAACLCVDGVFSLVCWSCENVESNWGCWRTQICP...,LVCWSCENVESNWGCWRTQICPDGFNYCATTYTGAGIGEYSAQSIS...,NaN,NaN,NaN,NaN,full_seq (SP)
1423,None|B.multicinctus_HiC_scaffold7_G00801.t1|Bu...,Ly6 other,Membrane,Elapidae,Elapidae,Bungarus,Bungarus multicinctus,8616,NaN,NaN,...,NaN,no,MLS,MLSDAGAAAASSSSSGPFSRHRPLTMKPLFAALLAGLLCMQTAMSS...,SLICISCDKVDHNSKCYDLKVCDEDNDRYCYTKYFGTGSGENHKEM...,NaN,NaN,NaN,NaN,full_seq (SP)
1424,None|denovo_2_scaffold7|Bungarus_multicinctus,Plesiotypic,Secreted,Elapidae,Elapidae,Bungarus,Bungarus multicinctus,8616,NaN,NaN,...,NaN,no,MKT,MKTLLLILVVVTLVCPDLAHTLICHSCTGALCPGHEQCPDGQKLCY...,LICHSCTGALCPGHEQCPDGQKLCYGKWNKTDVFIIRGCAATCPTE...,NaN,NaN,NaN,NaN,full_seq (SP)
1425,None|ScVE01q_1072_HRSCAF_1231_-_32|Naja_naja,Short-chain,Secreted,Elapidae,Elapidae,Naja,Naja naja,35670,NaN,NaN,...,NaN,no,MKT,MKTLLLTLVVVTIVCLDLGYTLKCHNTQLPLIYKTCPEGKNLCFKM...,LKCHNTQLPLIYKTCPEGKNLCFKMTLKRFPLKFPVKRGCAATCPK...,NaN,NaN,NaN,NaN,full_seq (SP)
1426,None|ScVE01q_1072_HRSCAF_1231_-_33|Naja_naja,Short-chain,Secreted,Elapidae,Elapidae,Naja,Naja naja,35670,NaN,NaN,...,NaN,no,MKT,MKTLLLTLVVVTIVCLDLGSTLKCNKLIPLAYKTCPAGKNLCYKMY...,LKCNKLIPLAYKTCPAGKNLCYKMYMVGCIDVCPKNSLLVKYVCCN...,NaN,NaN,NaN,NaN,full_seq (SP)

In [32]:
scolop = pd.read_csv('data/scolop.csv')
scolop

,identifier,Protein families,Fragment,Scoloptoxin?,protein_category
0,A0A0N7CSQ4,other,full_seq (SP),other,scoloptoxin
1,A0A1L4BJ98,Arthropod phospholipase D family,full_seq (SP),other,phospholipase_other
2,A0A6B7FMR5,Venom metalloproteinase (M12B) family,full_seq (SP),other,metalloproteinase
3,A0S864,Snake three-finger toxin family,full_seq (SP),3FTX,three_finger_toxin
4,A8YPR6,Natriuretic peptide family,full_seq (SP),other,NaN
...,...,...,...,...,...
1388,W4VSB6,other,full_seq (SP),other,conotoxin
1389,W4VSB9,other,full_seq (SP),other,neurotoxin
1390,W4VSG7,other,full_seq (SP),other,conotoxin
1391,W4VSI6,other,full_seq (SP),other,neurotoxin
1392,P0DPX5,other,full_seq (SP),Scoloptoxin,scoloptoxin

In [33]:
scolop = scolop.loc[scolop["Scoloptoxin?"] == "Scoloptoxin"]
scolop

     identifier Protein families       Fragment Scoloptoxin? protein_category
417      I6R1R5            other  full_seq (SP)  Scoloptoxin      scoloptoxin
1157     P0DPX7            other  full_seq (SP)  Scoloptoxin      scoloptoxin
1158     P0DPX8            other  full_seq (SP)  Scoloptoxin      scoloptoxin
1159     P0DPX9            other  full_seq (SP)  Scoloptoxin      scoloptoxin
1160     P0DPY0            other  full_seq (SP)  Scoloptoxin      scoloptoxin
1161     P0DPY1            other  full_seq (SP)  Scoloptoxin      scoloptoxin
1392     P0DPX5            other  full_seq (SP)  Scoloptoxin      scoloptoxin

In [34]:
fasta_dict = {record.id: str(record.seq) for record in SeqIO.parse("data/scolop.fasta", "fasta")}

scolop["full_seq"] = scolop["identifier"].map(fasta_dict)

/var/folders/6k/gr_1_h_97154rq71pm_q3jn40000gn/T/ipykernel_68824/799783804.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  scolop["full_seq"] = scolop["identifier"].map(fasta_dict)

In [35]:
scolop

,identifier,Protein families,Fragment,Scoloptoxin?,protein_category,full_seq
417,I6R1R5,other,full_seq (SP),Scoloptoxin,scoloptoxin,MPSLCIIALFGTLTFYTLIPSIHTLKCVRCDGPMSNYDCKTTYPAA...
1157,P0DPX7,other,full_seq (SP),Scoloptoxin,scoloptoxin,MNVLYTKIFFILILTRTSSALKCVQCFTGYGNIVQDCNKTSYSEPK...
1158,P0DPX8,other,full_seq (SP),Scoloptoxin,scoloptoxin,MLSLGVSIFLLVFLIPENSGLECYQCTWMKNSQSPDNCYKNLPNAT...
1159,P0DPX9,other,full_seq (SP),Scoloptoxin,scoloptoxin,MTFVVAAVVLLTVVPLATPLKCVQCDGPLTEFDCKTTVPEAKDCPQ...
1160,P0DPY0,other,full_seq (SP),Scoloptoxin,scoloptoxin,MRSWFVFVALLAVVFLPSSLDALKCIQCDSQPNRDECKTTLPEARD...
1161,P0DPY1,other,full_seq (SP),Scoloptoxin,scoloptoxin,MNPLNLSTFIVFTLFAASATTALTCFQCTTSEGSDYCVSSFPKPSQ...
1392,P0DPX5,other,full_seq (SP),Scoloptoxin,scoloptoxin,MPSLCIIALFGTLTFYTLIPSIHTLKCVICDSPMGNYDCKTTYPAA...

In [36]:
scolop["Fragment"] = scolop["full_seq"].apply(lambda x: "full_seq (SP)" if pd.notna(x) else "mature_seq (NO_SP)")

upar = pd.concat([upar, scolop], ignore_index=True)
upar

/var/folders/6k/gr_1_h_97154rq71pm_q3jn40000gn/T/ipykernel_68824/1210914211.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  scolop["Fragment"] = scolop["full_seq"].apply(lambda x: "full_seq (SP)" if pd.notna(x) else "mature_seq (NO_SP)")

,identifier,group,membran_prediction,taxon_of_interest,family,genus,species,taxon_id,db,uniprot_id,...,full_seq,mature_seq,pdb_id,LDDT,TM_score,RMSD,Fragment,Protein families,Scoloptoxin?,protein_category
0,None|Xetr_1|Xenopus_tropicalis,frog Ly6,Membrane,Anura,Pipidae,Xenopus,Xenopus tropicalis,8364.0,NaN,NaN,...,MAALYISLLLAALCIGTAVPLRCYTCTGATNANCLTQTDCGSTNTS...,LRCYTCTGATNANCLTQTDCGSTNTSCATVVGSVLGQPIIIKSCTL...,NaN,NaN,NaN,NaN,full_seq (SP),NaN,NaN,NaN
1,None|Xetr_2|Xenopus_tropicalis,frog Ly6,Secreted,Anura,Pipidae,Xenopus,Xenopus tropicalis,8364.0,NaN,NaN,...,MQCYMCLGATSNANCLTPTTCRSYDAYCQTVSSASITKYCAPSCTP...,MQCYMCLGATSNANCLTPTTCRSYDAYCQTVSSASITKYCAPSCTP...,NaN,NaN,NaN,NaN,full_seq (SP),NaN,NaN,NaN
2,None|Xetr_3|Xenopus_tropicalis,frog Ly6,Membrane,Anura,Pipidae,Xenopus,Xenopus tropicalis,8364.0,NaN,NaN,...,NaN,LKCYTCTSAPTNAECLTLTTCRSYDAYCETVVRSSSIARASGTISC...,NaN,NaN,NaN,NaN,mature_seq (NO_SP),NaN,NaN,NaN
3,None|Xetr_5|Xenopus_tropicalis,frog Ly6,Membrane,Anura,Pipidae,Xenopus,Xenopus tropicalis,8364.0,NaN,NaN,...,MADLRVVLVLTALCIGTAVSLTCYTCSGQSTNTNCMTATNCTASQT...,LTCYTCSGQSTNTNCMTATNCTASQTYCKTSVIAGGIGSLSAATIT...,NaN,NaN,NaN,NaN,full_seq (SP),NaN,NaN,NaN
4,None|Xetr_6|Xenopus_tropicalis,frog Ly6,Membrane,Anura,Pipidae,Xenopus,Xenopus tropicalis,8364.0,NaN,NaN,...,MSPYRYKGEYKGELGELGTHSTATPSLTMAALYGSLLLAALCIGTA...,LKCYTCTGESSNANCLNQTNCSDIDTSCQTFVASISLFGVSAKSIT...,NaN,NaN,NaN,NaN,full_seq (SP),NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,P0DPX8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,MLSLGVSIFLLVFLIPENSGLECYQCTWMKNSQSPDNCYKNLPNAT...,NaN,NaN,NaN,NaN,NaN,full_seq (SP),other,Scoloptoxin,scoloptoxin
1430,P0DPX9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,MTFVVAAVVLLTVVPLATPLKCVQCDGPLTEFDCKTTVPEAKDCPQ...,NaN,NaN,NaN,NaN,NaN,full_seq (SP),other,Scoloptoxin,scoloptoxin
1431,P0DPY0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,MRSWFVFVALLAVVFLPSSLDALKCIQCDSQPNRDECKTTLPEARD...,NaN,NaN,NaN,NaN,NaN,full_seq (SP),other,Scoloptoxin,scoloptoxin
1432,P0DPY1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,MNPLNLSTFIVFTLFAASATTALTCFQCTTSEGSDYCVSSFPKPSQ...,NaN,NaN,NaN,NaN,NaN,full_seq (SP),other,Scoloptoxin,scoloptoxin
1433,P0DPX5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,MPSLCIIALFGTLTFYTLIPSIHTLKCVICDSPMGNYDCKTTYPAA...,NaN,NaN,NaN,NaN,NaN,full_seq (SP),other,Scoloptoxin,scoloptoxin

In [40]:
upar["mature_seq"].value_counts()

mature_seq
LRCYTCTGATNANCLTQTDCGSTNTSCATVVGSVLGQPIIIKSCTLNCTPRSSSSARGTSTISCCNTDLCNGATGVKYTYPALGLSLGFLLVLLRGSAL    1
DFGHTLLCFNDHGYIGKTTETCEDGITICYQQSWRDFRGDRIERGCGCPDEKKGIELKCCNCDKCNG                                    1
LICYNNNGYKTTETCENGVTTCFEENWQSFYGIRIDRGCGCPKKKYIKLKCCKRDRCNG                                            1
LLCYTHMSNSAETTECCQNGKTTCYTKIWSDFRGTVIERGCGCPDKKYGGKINCCATDKCNS                                         1
KTCYKYLSYLVQATETCPDGQNLCYKRWHMLVPGRYDIARGCAATCPIAKNHYIVKCCAEDNCNY                                      1
                                                                                                      ..
LICVKERFLFSETTETCPDGQNICFNQGHLIYPGKYERTRGCAATCPILKTRDVIYCCSTDKCN                                       1
CLDLGYTLTCVKERSIYGDTFETCSAGQNLCFRRWHLVYPRKYDITRGCAATCPTAENNDTIDCCSADKCN                                1
TKCYNHLSRTPETTEICPDSDYFCYKISWIDGGEGRIERGCTFTCPELRPNGKYVYCCKRDKCNQ                                      1
RKCITKYSLGKETSQTCLAGQTLCFKKWKKGKKILRGCTAACPKPKKHESIQCCAKNKCNV                                          1
LKCNKLIPLAYKTCPAGKNLCYKMYMVGCIDVCPKNSLLVKYVCCNTDRCN                                                    1
Name: count, Length: 1427, dtype: int64

In [38]:
upar.to_csv("data/upar.csv", columns=["identifier", "group", "taxon_of_interest","family", "genus", "species", "Fragment", "Scoloptoxin?"], index=False)

In [39]:
with open("data/upar.fasta", "w") as f:
    for _, row in upar.iterrows():
        sequence = row["full_seq"] if "full_seq (SP)" in row["Fragment"] else row["mature_seq"]
        f.write(f">{row['identifier']}\n{sequence}\n")